module.exports = {
	FETCH_ALL: 'ASSEMBLY_DIAGRAM/FETCH_ALL',
	FETCH_BY_ID: 'ASSEMBLY_DIAGRAM/FETCH_BY_ID',
	CREATE: 'ASSEMBLY_DIAGRAM/CREATE',
	EDIT: 'ASSEMBLY_DIAGRAM/EDIT',
	CLEAN: 'ASSEMBLY_DIAGRAM/CLEAN',
	DELETE: 'ASSEMBLY_DIAGRAM/DELETE',
}
