module.exports = {
	FETCH_ALL: 'MENU_ITEM/FETCH_ALL',
	FETCH_BY_ID: 'MENU_ITEM/FETCH_BY_ID',
	CREATE: 'MENU_ITEM/CREATE',
	EDIT: 'MENU_ITEM/EDIT',
	CLEAN: 'MENU_ITEM/CLEAN',
	DELETE: 'MENU_ITEM/DELETE',
}
