module.exports = {
	FETCH_ALL: 'PAYMENT_OPTION/FETCH_ALL',
	FETCH_BY_ID: 'PAYMENT_OPTION/FETCH_BY_ID',
	CREATE: 'PAYMENT_OPTION/CREATE',
	EDIT: 'PAYMENT_OPTION/EDIT',
	CLEAN: 'PAYMENT_OPTION/CLEAN',
	DELETE: 'PAYMENT_OPTION/DELETE',
}
