module.exports = {
	FETCH_ALL: 'PROMOTION/FETCH_ALL',
	FETCH_BY_ID: 'PROMOTION/FETCH_BY_ID',
	CREATE: 'PROMOTION/CREATE',
	EDIT: 'PROMOTION/EDIT',
	CLEAN: 'PROMOTION/CLEAN',
	DELETE: 'PROMOTION/DELETE',
}
