module.exports = {
	FETCH_ALL: 'RESTAURANT/FETCH_ALL',
	FETCH_BY_ID: 'RESTAURANT/FETCH_BY_ID',
	EDIT: 'RESTAURANT/EDIT',
	ACTIVATE: 'RESTAURANT/ACTIVATE',
	PAID: 'RESTAURANT/PAID',
	CLEAN: 'USER/CLEAN',
}
