module.exports = {
	FETCH_ALL: 'VEGETABLE/FETCH_ALL',
	FETCH_BY_ID: 'VEGETABLE/FETCH_BY_ID',
	CREATE: 'VEGETABLE/CREATE',
	EDIT: 'VEGETABLE/EDIT',
	CLEAN: 'VEGETABLE/CLEAN',
	DELETE: 'VEGETABLE/DELETE',
}
