module.exports = {
	PIECE_PRODUCT: 'DIAGRAM_1',
	PIECE_PRODUCT_AND_ONE_SAUCE: 'DIAGRAM_5',
	PIECE_PRODUCT_AND_ONE_SWEET_SAUCE: 'DIAGRAM_6',
	SANDWICH_SIX_INCH: 'DIAGRAM_2',
	SANDWICH_FOOT_LONG: 'DIAGRAM_8',
	WRAP: 'DIAGRAM_3',
	SALAD: 'DIAGRAM_4',
	BREAKFAST: 'DIAGRAM_7',
	SANDWICH_WITHOUT_EXTRAS: 'DIAGRAM_9',
}
