const express = require('express')
const bodyParser = require('body-parser')
const passport = require('passport')
const cors = require('cors')
const morgan = require('morgan')

const authorizationRoutes = require('./routes/authorization.routes')
const assemblyDiagramRoutes = require('./routes/assemblyDiagram.routes')
const breadRoutes = require('./routes/bread.routes')
const extraRoutes = require('./routes/extra.routes')
const menuItemRoutes = require('./routes/menuItem.routes')
const sauceRoutes = require('./routes/sauce.routes')
const spiceRoutes = require('./routes/spice.routes')
const vegetableRoutes = require('./routes/vegetable.routes')
const productRoutes = require('./routes/product.routes')
const unitRoutes = require('./routes/unit.routes')
const userRoutes = require('./routes/user.routes')
const paymentOptionRoutes = require('./routes/paymentOption.routes')
const restaurantRoutes = require('./routes/restaurant.routes')
const addressRoutes = require('./routes/address.routes')
const menuRoutes = require('./routes/menu.routers')
const orderRoutes = require('./routes/order.routes')
const promotionRoutes = require('./routes/promotion.routes')

const app = express()

app.use(passport.initialize())
require('./middleware/passport')(passport)

app.use(morgan('dev'))
app.use('/uploads', express.static('uploads'))
app.use('/images', express.static('images'))
app.use(bodyParser.urlencoded({extended: true}))
app.use(bodyParser.json())

app.use(cors())

app.use('/api/authorization', authorizationRoutes)
app.use('/api/assembly-diagram', assemblyDiagramRoutes)
app.use('/api/bread', breadRoutes)
app.use('/api/extra', extraRoutes)
app.use('/api/menu-item', menuItemRoutes)
app.use('/api/sauce', sauceRoutes)
app.use('/api/spice', spiceRoutes)
app.use('/api/vegetable', vegetableRoutes)
app.use('/api/product', productRoutes)
app.use('/api/unit', unitRoutes)
app.use('/api/user', userRoutes)
app.use('/api/payment-option', paymentOptionRoutes)
app.use('/api/restaurant', restaurantRoutes)
app.use('/api/address', addressRoutes)
app.use('/api/menu', menuRoutes)
app.use('/api/order', orderRoutes)
app.use('/api/promotion', promotionRoutes)

module.exports = app
