module.exports = {
	BREAD: 'images/no_image_bread.jpg',
	EXTRA: 'images/no_extra_image.jpg',
	MENU_ITEM: 'images/no_photo_menu_item.jpg',
	SAUCE: 'images/no_image_sauce.jpg',
	VEGETABLE: 'images/no_image_vegetable.jpg',
	ASSEMBLY_DIAGRAM: 'images/no_image_assembly_diagram.jpg',
	SPICE: 'images/no_image_spice.jpg',
	PRODUCT: 'images/no_image_product.jpg',
	SIX_INCH: 'images/no_image_unit.jpg',
	FOOT_LONG: 'images/no_image_unit.jpg',
	WRAP: 'images/no_image_unit.jpg',
	SALAD: 'images/no_image_unit.jpg',
	PROMOTION: 'images/no_image_promotion.jpg',
}
