module.exports = {
	SHOW_ERROR: 'SHOW_ERROR',
	HIDE_ERROR: 'HIDE_ERROR',
	SHOW_SUCCESS: 'SHOW_SUCCESS',
	HIDE_SUCCESS: 'HIDE_SUCCESS',
	SHOW_LOADER: 'SHOW_LOADER',
	HIDE_LOADER: 'HIDE_LOADER',
	SET_TOKEN: 'SET_TOKEN',
	CREATE_ERROR: 'CREATE_ERROR',
}
