module.exports = {
	FETCH_MENU_ITEMS: 'DATA_FOR_MENU/FETCH_MENU_ITEMS',
	FETCH_ASSEMBLY_DIAGRAMS: 'DATA_FOR_MENU/FETCH_ASSEMBLY_DIAGRAMS',
	FETCH_BREADS: 'DATA_FOR_MENU/FETCH_BREADS',
	FETCH_EXTRAS: 'DATA_FOR_MENU/FETCH_EXTRAS',
	FETCH_VEGETABLES: 'DATA_FOR_MENU/FETCH_VEGETABLES',
	FETCH_SAUCES: 'DATA_FOR_MENU/FETCH_SAUCES',
	FETCH_SPICES: 'DATA_FOR_MENU/FETCH_SPICES',
	FETCH_UNITS: 'DATA_FOR_MENU/FETCH_UNITS',
	FETCH_PRODUCTS: 'DATA_FOR_MENU/FETCH_PRODUCTS',
	CLEAN: 'DATA_FOR_MENU/CLEAN',
}
