module.exports = {
	FETCH_ALL: 'RESTAURANT/FETCH_ALL',
	FETCH_BY_ID: 'RESTAURANT/FETCH_BY_ID',
	CREATE: 'RESTAURANT/CREATE',
	ACTIVATE: 'RESTAURANT/ACTIVATE',
	EDIT: 'RESTAURANT/EDIT',
	CLEAN: 'RESTAURANT/CLEAN',
	DELETE: 'RESTAURANT/DELETE',
}
