module.exports = {
	SHOW_ERROR: 'SHOW_ERROR',
	HIDE_ERROR: 'HIDE_ERROR',
	SHOW_SUCCESS: 'SHOW_SUCCESS',
	HIDE_SUCCESS: 'HIDE_SUCCESS',
	SHOW_LOADER: 'SHOW_LOADER',
	HIDE_LOADER: 'HIDE_LOADER',
	SET_URL: 'SET_URL',
	SET_HEADER_HEIGHT: 'SET_HEADER_HEIGHT',
	SET_FOOTER_HEIGHT: 'SET_FOOTER_HEIGHT',
	ORDER: 'ORDER',
}
