module.exports = {
	SET_SERVICE: 'SET_SERVICE',
	SET_NAME: 'SET_NAME',
	SET_COMMENT: 'SET_COMMENT',
	SET_PAYMENT: 'SET_PAYMENT',
	SET_PHONE: 'SET_PHONE',
	SET_ADDRESS: 'SET_ADDRESS',
	SET_USER_TIME: 'SET_USER_TIME',
	SET_IS_PROMOTION: 'SET_IS_PROMOTION',
	CLEAN_ORDER: 'CLEAN_ORDER',
	CLEAN_ORDER_ERROR: 'CLEAN_ORDER_ERROR',
}
